# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='management.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('start_data', models.DateField(blank=True, null=True)),
                ('end_data', models.DateField(blank=True, null=True)),
                ('importance', models.TextField()),
                ('abstract', models.TextField()),
                ('result', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='management.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='management.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('output', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'دانش فنی'), ('item_key2', 'ساخت'), ('item_key3', 'فرآیند'), ('item_key4', 'انسانی'), ('item_key5', 'ارتباطی'), ('item_key6', 'ساختاری'), ('item_key7', 'ذینفعان'), ('item_key8', 'نوآوری و فناوری'), ('item_key9', 'روش های یادگیری')], max_length=89)),
                ('implicit_scientific_pen', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'درس های آموخته شده'), ('item_key2', 'مشکلات و ریسک های انجام شده'), ('item_key3', 'فرآیندها و روش های اجرایی'), ('item_key4', 'سایر')], max_length=39)),
                ('explicit_scientific_pen', multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'الگوها و قالب ها'), ('item_key2', 'چک لیست ها'), ('item_key3', 'راهنماها و دستورالعمل ها'), ('item_key4', 'گزارش ها و وقایع نگارها'), ('item_key5', 'سایر'), ('item_key6', 'آیا برای انجام کار نیاز به نیروی دانشگر می باشد')], max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('is_main', models.BooleanField(verbose_name='نوع:')),
                ('main_area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_area', to='management.ScientificActivity')),
            ],
        ),
    ]
